# Generated by Django 5.0.4 on 2024-09-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='suggested_titles',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
