# Generated by Django 5.0.4 on 2024-09-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_suggested_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='suggested_titles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
